syntax = "proto3";

package api;

import "google/protobuf/timestamp.proto";

// State that changes often but also is not security-critical,
// and therefore can be wiped and overwritten without much consequence if needed.
message WebauthnVolatileState {
    repeated WebauthnCredentialState credentials = 1;
}

message WebauthnCredentialState {
    string                    id            = 1; // base64.RawURLEncoding.EncodeToString(credential ID)
    uint32                    sign_count    = 2;
    google.protobuf.Timestamp last_use_time = 3;
}
